name: ReadTheDocs CI

on:
  push:
    branches:
    - master
    - release/*
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:

  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        # GitHub CI installs pip3 and setuptools outside the path.
        # Update the path to include them and run.
        PATH=/home/runner/.local/bin:$PATH pip3 install --user -r ./docs/requirements.txt
        cd ./docs && PATH=/home/runner/.local/bin:$PATH build-docs -l en

  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Deploy
      env:
        DOCS_BUILD_DIR: "${./docs/_build/"
      run: |
        PATH=/home/runner/.local/bin:$PATH source ./docs/utils.sh
        PATH=/home/runner/.local/bin:$PATH add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
        PATH=/home/runner/.local/bin:$PATH export GIT_VER=$(git describe --always)
        PATH=/home/runner/.local/bin:$PATH pip install -r ./docs/requirements.txt --prefer-binary
        cd ./docs && PATH=/home/runner/.local/bin:$PATH build-docs -l en
        PATH=/home/runner/.local/bin:$PATH deploy-docs


