name: ESP32 Arduino CI

on: [push]

jobs:

  build-arduino-0:
    name: Build Arduino IDE Tests 0
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        ESP32_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 0 9
    - name: Sketch Sizes
      run: cat size.log

  build-arduino-1:
    name: Build Arduino IDE Tests 1
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-arduino-ide.sh
    - name: Test Arduino IDE
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/test-arduino-ide.sh 1 9
    - name: Sketch Sizes
      run: cat size.log


  build-platformio:
    name: Build PlatformIO Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Run CMake Check
      run: ./tools/check_cmakelists.sh

    - name: Install Python Wheel
      run: pip install wheel
    - name: Install GCC Toolchain
      run: cd tools && python get.py
    - name: Install PlatformIO
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: ./tools/prep-platformio.sh
    - name: Test PlatformIO
      run: ./tools/test-platformio.sh
